### ISSUE TITLE
`ExpiredTokenError` not rescued in controllers/app.rb

### ISSUE THREAD

**Issue by nthu103060011** [ISS-Security/credence-api#12]
`ExpiredTokenError` from `authenticated_account` method is not rescued.
In `controllers/app.rb`:
```
route do |routing|
...
  begin
    @auth_account = authenticated_account(routing.headers)
  rescue AuthToken::InvalidTokenError
    routing.halt 403, { message: 'Invalid auth token' }.to_json
  end
```
`authenticated_account` in `helpers.rb` is calling `AuthToken.payload`, which can raise both `InvalidTokenError` and `ExpiredTokenError`.

**Comment by soumyaray** [comment]
Fixed in some parts but more to go I expect...

**Comment by soumyaray** [comment]
Closing for now — I think its mostly fixed :)
